# ----------------------------------------------------
# 1. JWT CONFIGURATION
# ----------------------------------------------------
stocktrace.jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongForJwtSigning12345

# ----------------------------------------------------
# 2. DATABASE CONNECTION (Aiven Cloud PostgreSQL)
# ----------------------------------------------------
spring.datasource.url=jdbc:postgres://avnadmin:AVNS_jSbUqkhE3ce8XP5XNwt@pg-3f2c09b-latifaelguerouani-7110.f.aivencloud.com:22609/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_jSbUqkhE3ce8XP5XNwt
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------------------
# 3. JPA CONFIGURATION
# ----------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ----------------------------------------------------
# 4. SERVER CONFIG
# ----------------------------------------------------
server.port=8080
