# ----------------------------------------------------
# 1. DATABASE CONNECTION (Aiven Cloud PostgreSQL)
# ----------------------------------------------------
# JWT
stocktrace.jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongForJwtSigning12345

# Database (Replace with your actual remote database details)
spring.datasource.url=jdbc:postgresql://pg-3f2c09b-latifaelguerouani-7110.f.aivencloud.com:5432/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_jSbUqkhE3ce8XP5XNwt
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------------------
# 2. JPA / HIBERNATE CONFIGURATION
# ----------------------------------------------------
# Auto-create / update tables f-Cloud Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ----------------------------------------------------
# 3. SERVER CONFIG
# ----------------------------------------------------
server.port=8080
